name: mirrorchyan

on:
  workflow_dispatch:

jobs:
  mirrorchyan:
    runs-on: macos-latest
    steps:
      - id: uploading
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "MaaJR-win-x86_64-*.zip"
          pick_files: '["resource", "interface.json"]'
          exclude_files: '["resource/base/model/ocr/**"]'
          mirrorchyan_rid: MaaJR

          owner: Saratoga-Official
          repo: MaaJR
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
