name: Publish Changelog

on:
  release:
    types: [created]

jobs:
  publish-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read CHANGELOG.md
        id: changelog
        run: echo "CHANGELOG=$(cat CHANGELOG.md)" >> $GITHUB_ENV

      - name: Update release notes with full CHANGELOG
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: CHANGELOG.md